// Life in the UK Test — All Q&A data from Exams 1–17
// Bilingual: English + Traditional Chinese (繁體中文) for Hongkongers
// Source: lifeintheuktestweb.co.uk

// Era names in Chinese (used by timeline filter buttons)
const ERA_ZH = {
  "Prehistoric":        "史前時代",
  "Roman Britain":      "羅馬統治時期",
  "Anglo-Saxon & Viking": "盎格魯-撒克遜及維京時代",
  "Norman Conquest":    "諾曼征服",
  "Medieval":           "中世紀",
  "Tudor":              "都鐸王朝",
  "Stuart":             "斯圖亞特王朝",
  "18th Century":       "18世紀",
  "19th Century":       "19世紀",
  "Early 20th Century": "20世紀初",
  "Post-War & Modern":  "戰後及現代"
};

// ─────────────────────────────────────────────────────────────────
// REGIONS TABLE
// ─────────────────────────────────────────────────────────────────
const REGIONS_TABLE = [

  { category: "Symbols & Identity", category_zh: "象徵與身份" },
  {
    question: "Patron Saint?", question_zh: "守護聖人？",
    england: "St George",  england_zh: "聖喬治",
    scotland: "St Andrew", scotland_zh: "聖安德魯",
    wales: "St David",     wales_zh: "聖大衛",
    ni: "St Patrick",      ni_zh: "聖柏德烈",
    exams: [1,3,5,10]
  },
  {
    question: "Patron Saint's Day?", question_zh: "守護聖人節日？",
    england: "23rd April",     england_zh: "4月23日",
    scotland: "30th November", scotland_zh: "11月30日",
    wales: "1st March",        wales_zh: "3月1日",
    ni: "17th March",          ni_zh: "3月17日",
    exams: [8,11,13,14]
  },
  {
    question: "Patron Saint's Day — public holiday?", question_zh: "守護聖人日是公眾假期嗎？",
    england: "No",  england_zh: "否",
    scotland: "No", scotland_zh: "否",
    wales: "No",    wales_zh: "否",
    ni: "Yes",      ni_zh: "是",
    exams: [2]
  },
  {
    question: "Capital City?", question_zh: "首都／首府？",
    england: "London",    england_zh: "倫敦",
    scotland: "Edinburgh",scotland_zh: "愛丁堡",
    wales: "Cardiff",     wales_zh: "卡迪夫",
    ni: "Belfast",        ni_zh: "貝爾法斯特",
    exams: [3,7,9]
  },
  {
    question: "Flower Symbol?", question_zh: "花卉象徵？",
    england: "Rose",     england_zh: "玫瑰",
    scotland: "Thistle", scotland_zh: "薊花",
    wales: "Daffodil",   wales_zh: "水仙花",
    ni: "Shamrock",      ni_zh: "三葉草",
    exams: [4,8,9,16]
  },

  { category: "Religion & Church", category_zh: "宗教與教會" },
  {
    question: "Own established church?", question_zh: "有自己的國家教會嗎？",
    england: "Yes — Church of England",  england_zh: "有 — 英格蘭教會",
    scotland: "Yes — Presbyterian",      scotland_zh: "有 — 長老教會",
    wales: "No",    wales_zh: "否",
    ni: "No",       ni_zh: "否",
    exams: [3,5,6,10]
  },
  {
    question: "Head of the Church of England?", question_zh: "英格蘭教會的首領？",
    england: "The Monarch", england_zh: "君主",
    scotland: "—", scotland_zh: "—", wales: "—", wales_zh: "—", ni: "—", ni_zh: "—",
    exams: [4]
  },
  {
    question: "Spiritual leader of Church of England?", question_zh: "英格蘭教會的精神領袖？",
    england: "Archbishop of Canterbury", england_zh: "坎特伯雷大主教",
    scotland: "—", scotland_zh: "—", wales: "—", wales_zh: "—", ni: "—", ni_zh: "—",
    exams: [13]
  },
  {
    question: "When was a Protestant church established?", question_zh: "何時建立新教教會？",
    england: "1534 (Church of England)", england_zh: "1534年（英格蘭教會）",
    scotland: "1560",                    scotland_zh: "1560年",
    wales: "—", wales_zh: "—", ni: "—", ni_zh: "—",
    exams: [3,11]
  },

  { category: "Government & Devolution", category_zh: "政府與權力下放" },
  {
    question: "Own Parliament / Assembly?", question_zh: "有自己的議會／議事機構嗎？",
    england: "— (Westminster)",          england_zh: "—（西敏寺議會）",
    scotland: "Scottish Parliament",     scotland_zh: "蘇格蘭議會",
    wales: "Welsh Assembly",             wales_zh: "威爾斯議會",
    ni: "Northern Ireland Assembly",     ni_zh: "北愛爾蘭議會",
    exams: [16]
  },
  {
    question: "Number of members?", question_zh: "成員人數？",
    england: "—", england_zh: "—", scotland: "—", scotland_zh: "—",
    wales: "60",  wales_zh: "60人",
    ni: "90",     ni_zh: "90人",
    exams: [10,12]
  },
  {
    question: "Elected every?", question_zh: "選舉週期？",
    england: "—", england_zh: "—", scotland: "—", scotland_zh: "—",
    wales: "4 years", wales_zh: "每4年",
    ni: "—", ni_zh: "—",
    exams: [8]
  },
  {
    question: "Election method?", question_zh: "選舉方式？",
    england: "—", england_zh: "—", scotland: "—", scotland_zh: "—", wales: "—", wales_zh: "—",
    ni: "Proportional representation", ni_zh: "比例代表制",
    exams: [14]
  },
  {
    question: "Can legislate on: Health & Education?", question_zh: "可就醫療及教育立法？",
    england: "—", england_zh: "—",
    scotland: "Yes", scotland_zh: "是",
    wales: "Yes",    wales_zh: "是",
    ni: "Yes",       ni_zh: "是",
    exams: [7]
  },
  {
    question: "Cannot legislate on?", question_zh: "不可立法的範疇？",
    england: "—", england_zh: "—",
    scotland: "Defence, Immigration", scotland_zh: "國防、移民",
    wales: "—", wales_zh: "—",
    ni: "Defence, Immigration",       ni_zh: "國防、移民",
    exams: [7,11]
  },
  {
    question: "Own banknotes (valid UK-wide)?", question_zh: "有自己的紙幣（全英有效）？",
    england: "—", england_zh: "—",
    scotland: "Yes", scotland_zh: "有",
    wales: "—",      wales_zh: "—",
    ni: "Yes",       ni_zh: "有",
    exams: [2,8]
  },

  { category: "Legal System", category_zh: "法律制度" },
  {
    question: "Court for minor criminal cases?", question_zh: "審理輕微刑事案件的法院？",
    england: "Magistrates' Court",         england_zh: "裁判法院",
    scotland: "Justice of the Peace Court",scotland_zh: "太平紳士法院",
    wales: "Magistrates' Court",           wales_zh: "裁判法院",
    ni: "Magistrates' Court",              ni_zh: "裁判法院",
    exams: [2,6]
  },
  {
    question: "Jury size?", question_zh: "陪審團人數？",
    england: "12",  england_zh: "12人",
    scotland: "15", scotland_zh: "15人",
    wales: "12",    wales_zh: "12人",
    ni: "12",       ni_zh: "12人",
    exams: [2,7]
  },
  {
    question: "Youth Court heard by?", question_zh: "青少年法庭由誰審理？",
    england: "Up to 3 magistrates or District Judge", england_zh: "最多3名裁判官或地區法官",
    scotland: "—", scotland_zh: "—",
    wales: "Up to 3 magistrates or District Judge",   wales_zh: "最多3名裁判官或地區法官",
    ni: "Up to 3 magistrates or District Judge",      ni_zh: "最多3名裁判官或地區法官",
    exams: [15,16,17]
  },
  {
    question: "Small claims max amount?", question_zh: "小額索償最高金額？",
    england: "£10,000", england_zh: "£10,000",
    scotland: "£5,000", scotland_zh: "£5,000",
    wales: "£10,000",   wales_zh: "£10,000",
    ni: "£5,000",       ni_zh: "£5,000",
    exams: [14,16]
  },

  { category: "Food & Traditions", category_zh: "飲食與傳統" },
  {
    question: "Traditional food?", question_zh: "傳統食物？",
    england: "—", england_zh: "—",
    scotland: "Haggis",   scotland_zh: "哈吉斯（雜碎布丁）",
    wales: "—",   wales_zh: "—",
    ni: "Ulster Fry",     ni_zh: "阿爾斯特炸早餐",
    exams: [6,14]
  },
  {
    question: "New Year's Eve name?", question_zh: "除夕夜的名稱？",
    england: "New Year's Eve", england_zh: "除夕夜",
    scotland: "Hogmanay",      scotland_zh: "火格馬內（蘇格蘭除夕節）",
    wales: "—", wales_zh: "—", ni: "—", ni_zh: "—",
    exams: [3,9,14]
  },
  {
    question: "New Year's Eve song (whole UK)?", question_zh: "全英跨年歌曲？",
    england: "Auld Lang Syne",  england_zh: "友誼萬歲",
    scotland: "Auld Lang Syne", scotland_zh: "友誼萬歲",
    wales: "Auld Lang Syne",    wales_zh: "友誼萬歲",
    ni: "Auld Lang Syne",       ni_zh: "友誼萬歲",
    exams: [15]
  },

  { category: "Geography & Landmarks", category_zh: "地理與地標" },
  {
    question: "Famous National Park?", question_zh: "著名國家公園？",
    england: "Lake District (largest in England)", england_zh: "湖區（英格蘭最大）",
    scotland: "Loch Lomond & The Trossachs",       scotland_zh: "洛蒙德湖及特羅薩克斯",
    wales: "Snowdonia",                            wales_zh: "斯諾登尼亞",
    ni: "—", ni_zh: "—",
    exams: [3,10,13]
  },
  {
    question: "Famous prehistoric site?", question_zh: "著名史前遺址？",
    england: "Stonehenge (Wiltshire)", england_zh: "巨石陣（威爾特郡）",
    scotland: "Skara Brae",            scotland_zh: "斯卡拉布雷",
    wales: "—", wales_zh: "—", ni: "—", ni_zh: "—",
    exams: [14,17]
  },
  {
    question: "Famous natural landmark?", question_zh: "著名自然地標？",
    england: "—", england_zh: "—", scotland: "—", scotland_zh: "—", wales: "—", wales_zh: "—",
    ni: "Giant's Causeway", ni_zh: "巨人之路",
    exams: [16]
  },
  {
    question: "Famous castle / historic building?", question_zh: "著名城堡／歷史建築？",
    england: "Tower of London", england_zh: "倫敦塔",
    scotland: "Crathes Castle", scotland_zh: "克拉西斯城堡",
    wales: "Caernarfon Castle", wales_zh: "卡那封城堡",
    ni: "—", ni_zh: "—",
    exams: [6,13]
  },
  {
    question: "Cultural / festival location?", question_zh: "文化／節慶地點？",
    england: "London West End (Theatreland)", england_zh: "倫敦西區（劇院區）",
    scotland: "Edinburgh (Fringe Festival)",  scotland_zh: "愛丁堡（藝穗節）",
    wales: "Cardiff / Swansea",               wales_zh: "卡迪夫／斯旺西",
    ni: "Belfast",                            ni_zh: "貝爾法斯特",
    exams: [3,6,10,11]
  },

  { category: "Sport", category_zh: "體育運動" },
  {
    question: "Sport originated here?", question_zh: "源自此地的運動？",
    england: "Cricket (The Ashes)", england_zh: "板球（英澳對抗賽）",
    scotland: "Golf",               scotland_zh: "高爾夫球",
    wales: "—", wales_zh: "—", ni: "—", ni_zh: "—",
    exams: [2,5,7]
  },
  {
    question: "Famous horse racing event / venue?", question_zh: "著名賽馬活動／場地？",
    england: "Royal Ascot; Newmarket (National Horseracing Museum)", england_zh: "皇家雅士谷；紐馬基特（國家賽馬博物館）",
    scotland: "Ayr (Scottish Grand National)", scotland_zh: "艾爾（蘇格蘭大賽馬）",
    wales: "—", wales_zh: "—", ni: "—", ni_zh: "—",
    exams: [7,10,13]
  },
  {
    question: "Famous tennis tournament?", question_zh: "著名網球賽事？",
    england: "Wimbledon", england_zh: "溫布頓",
    scotland: "—", scotland_zh: "—", wales: "—", wales_zh: "—", ni: "—", ni_zh: "—",
    exams: [12]
  },

  { category: "Notable People", category_zh: "知名人物" },
  {
    question: "Famous inventor / scientist?", question_zh: "著名發明家／科學家？",
    england: "Isaac Newton (gravity); Frank Whittle (jet engine); Alan Turing (Turing machine); Tim Berners-Lee (WWW); Francis Crick (DNA); Ernest Rutherford (atom)",
    england_zh: "牛頓（重力）；惠特爾（噴射引擎）；圖靈（圖靈機）；伯納斯-李（萬維網）；克里克（DNA）；盧瑟福（分裂原子）",
    scotland: "John Logie Baird (TV); Alexander Fleming (penicillin)",
    scotland_zh: "貝爾德（電視）；弗萊明（青黴素）",
    wales: "—", wales_zh: "—", ni: "—", ni_zh: "—",
    exams: [1,2,10,12,15,16]
  },
  {
    question: "Famous writer / poet?", question_zh: "著名作家／詩人？",
    england: "William Shakespeare (Stratford-upon-Avon); William Wordsworth; Geoffrey Chaucer; William Caxton (printing)",
    england_zh: "莎士比亞（埃文河畔斯特拉特福）；華茲華斯；喬叟；卡克斯頓（印刷）",
    scotland: "Robert Burns", scotland_zh: "羅伯特·彭斯",
    wales: "—", wales_zh: "—", ni: "—", ni_zh: "—",
    exams: [2,6,9,11,13]
  },
  {
    question: "Famous political leader?", question_zh: "著名政治領袖？",
    england: "Winston Churchill; Margaret Thatcher (1st female PM); Oliver Cromwell; Sir Robert Walpole (1st PM)",
    england_zh: "邱吉爾；戴卓爾（首位女首相）；克倫威爾；沃波爾爵士（首位首相）",
    scotland: "Robert the Bruce; Bonnie Prince Charlie",
    scotland_zh: "羅伯特·布魯斯；英俊王子查理",
    wales: "—", wales_zh: "—", ni: "—", ni_zh: "—",
    exams: [1,2,4,7,11,13,14]
  },

  { category: "Key Historical Events", category_zh: "重要歷史事件" },
  {
    question: "Key battle?", question_zh: "重要戰役？",
    england: "Battle of Hastings 1066; Battle of Trafalgar 1805; Battle of Waterloo 1815",
    england_zh: "黑斯廷斯戰役（1066）；特拉法加戰役（1805）；滑鐵盧戰役（1815）",
    scotland: "Battle of Bannockburn 1314 (Robert the Bruce defeated English)",
    scotland_zh: "班諾克本戰役（1314）（羅伯特·布魯斯擊敗英格蘭）",
    wales: "—", wales_zh: "—",
    ni: "Battle of the Boyne 1690 (James II defeated)",
    ni_zh: "博因河戰役（1690）（詹姆斯二世戰敗）",
    exams: [1,4,7,9,12,17]
  },
  {
    question: "Famous historic massacre / clearance?", question_zh: "著名歷史屠殺／清洗？",
    england: "—", england_zh: "—",
    scotland: "Glencoe Massacre (~1692); Highland Clearances",
    scotland_zh: "格倫科大屠殺（約1692）；高地清洗",
    wales: "—", wales_zh: "—", ni: "—", ni_zh: "—",
    exams: [7]
  },
  {
    question: "When did region join the Union?", question_zh: "地區何時加入聯合王國？",
    england: "—", england_zh: "—",
    scotland: "Act of Union 1707", scotland_zh: "1707年聯合法案",
    wales: "1536 (Laws in Wales Acts)", wales_zh: "1536年（威爾斯法案）",
    ni: "1800 (Acts of Union)",        ni_zh: "1800年（聯合法案）",
    exams: []
  },
];

// ─────────────────────────────────────────────────────────────────
// TIMELINE DATA
// ─────────────────────────────────────────────────────────────────
const TIMELINE_DATA = [
  // PREHISTORIC
  { period: "Stone Age", year: "~800,000 BC", era: "Prehistoric",
    fact: "First people in Britain were hunter-gatherers",
    fact_zh: "英國最早的居民是狩獵採集者", category: "Origins & Settlement", category_zh: "起源與定居", exams: [7] },
  { period: "Neolithic", year: "~4,000 BC", era: "Prehistoric",
    fact: "First farmers came to Britain from South-East Europe (~6,000 years ago)",
    fact_zh: "第一批農民約6,000年前從東南歐來到英國", category: "Origins & Settlement", category_zh: "起源與定居", exams: [2,15] },
  { period: "Iron Age", year: "~800 BC", era: "Prehistoric",
    fact: "First coins minted in Britain, showing names of Iron Age kings",
    fact_zh: "英國首批鑄幣印有鐵器時代國王的名字", category: "Trade & Empire", category_zh: "貿易與帝國", exams: [6,11,12] },
  { period: "Ancient", year: "~3,000 BC", era: "Prehistoric",
    fact: "Stonehenge built in Wiltshire",
    fact_zh: "巨石陣建於威爾特郡", category: "Origins & Settlement", category_zh: "起源與定居", exams: [14] },
  { period: "Ancient", year: "~3,000 BC", era: "Prehistoric",
    fact: "Skara Brae – prehistoric settlement in Scotland",
    fact_zh: "斯卡拉布雷——蘇格蘭史前定居地", category: "Origins & Settlement", category_zh: "起源與定居", exams: [17] },

  // ROMAN
  { period: "Roman", year: "55 BC", era: "Roman Britain",
    fact: "Julius Caesar led the first invasion of Britain",
    fact_zh: "尤利烏斯·凱撒率軍首次入侵英國", category: "Invasion & Conquest", category_zh: "入侵與征服", exams: [2] },
  { period: "Roman", year: "~AD 60", era: "Roman Britain",
    fact: "Boudicca – tribal leader who fought against the Romans",
    fact_zh: "布迪卡——對抗羅馬人的部落女首領", category: "Invasion & Conquest", category_zh: "入侵與征服", exams: [4,13,14] },
  { period: "Roman", year: "~AD 122", era: "Roman Britain",
    fact: "Emperor Hadrian built a wall in northern England to keep out the Picts",
    fact_zh: "哈德良皇帝在英格蘭北部修建城牆以抵禦皮克特人", category: "Invasion & Conquest", category_zh: "入侵與征服", exams: [10] },
  { period: "Roman", year: "AD 410", era: "Roman Britain",
    fact: "Romans left Britain",
    fact_zh: "羅馬人撤離英國", category: "Invasion & Conquest", category_zh: "入侵與征服", exams: [16] },

  // ANGLO-SAXON & VIKING
  { period: "Anglo-Saxon", year: "After AD 410", era: "Anglo-Saxon & Viking",
    fact: "The Jutes came to Britain from northern Europe after the Romans left",
    fact_zh: "朱特人在羅馬人撤離後從北歐來到英國", category: "Origins & Settlement", category_zh: "起源與定居", exams: [16] },
  { period: "Anglo-Saxon", year: "~9th century", era: "Anglo-Saxon & Viking",
    fact: "King Alfred the Great united Anglo-Saxon kingdoms and defeated the Vikings",
    fact_zh: "阿爾弗雷德大帝統一盎格魯-撒克遜王國並擊敗維京人", category: "Wars & Conflicts", category_zh: "戰爭與衝突", exams: [2,13] },

  // NORMAN
  { period: "Norman", year: "1066", era: "Norman Conquest",
    fact: "Battle of Hastings — last successful foreign invasion of England; the Norman Conquest",
    fact_zh: "黑斯廷斯戰役——最後一次成功的外族入侵英格蘭；諾曼征服", category: "Wars & Conflicts", category_zh: "戰爭與衝突", exams: [2,7] },
  { period: "Norman", year: "1066", era: "Norman Conquest",
    fact: "William the Conqueror (from France) built the Tower of London (White Tower)",
    fact_zh: "征服者威廉（來自法國）建造倫敦塔（白塔）", category: "Government & Law", category_zh: "政府與法律", exams: [6,16,17] },
  { period: "Norman", year: "~1086", era: "Norman Conquest",
    fact: "Domesday Book written after the Norman Conquest — tells how people lived in England",
    fact_zh: "《末日審判書》於諾曼征服後編成——記載英格蘭人民的生活", category: "Government & Law", category_zh: "政府與法律", exams: [11,15] },
  { period: "Norman", year: "Post-1066", era: "Norman Conquest",
    fact: "English language developed from Anglo-Saxon + Norman French",
    fact_zh: "英語由盎格魯-撒克遜語和諾曼法語發展而來", category: "Culture & Arts", category_zh: "文化與藝術", exams: [11,15] },

  // MEDIEVAL
  { period: "Medieval", year: "1215", era: "Medieval",
    fact: "Magna Carta created — restricted the King's power",
    fact_zh: "《大憲章》制定——限制國王的權力", category: "Government & Law", category_zh: "政府與法律", exams: [2,8] },
  { period: "Medieval", year: "~1300s", era: "Medieval",
    fact: "Geoffrey Chaucer wrote the Canterbury Tales",
    fact_zh: "喬叟著《坎特伯雷故事集》", category: "Culture & Arts", category_zh: "文化與藝術", exams: [4,10,13] },
  { period: "Medieval", year: "1314", era: "Medieval",
    fact: "Battle of Bannockburn — Robert the Bruce defeated the English; Scotland remained unconquered",
    fact_zh: "班諾克本戰役——羅伯特·布魯斯擊敗英格蘭；蘇格蘭維持獨立",
    category: "Wars & Conflicts", category_zh: "戰爭與衝突", exams: [7,12], forRegions: true },
  { period: "Medieval", year: "1348", era: "Medieval",
    fact: "Black Death (plague) — one third of the population of England died",
    fact_zh: "黑死病（鼠疫）——英格蘭三分之一人口死亡", category: "Society & Health", category_zh: "社會與健康", exams: [6,17] },
  { period: "Medieval", year: "~1337–1453", era: "Medieval",
    fact: "Hundred Years War with France",
    fact_zh: "與法國的百年戰爭", category: "Wars & Conflicts", category_zh: "戰爭與衝突", exams: [3] },
  { period: "Medieval", year: "~1455–1485", era: "Medieval",
    fact: "Wars of the Roses — House of York vs House of Lancaster",
    fact_zh: "玫瑰戰爭——約克家族對抗蘭開斯特家族", category: "Wars & Conflicts", category_zh: "戰爭與衝突", exams: [1] },

  // TUDOR
  { period: "Tudor", year: "~1476", era: "Tudor",
    fact: "William Caxton — first person to print books in England using a printing press",
    fact_zh: "威廉·卡克斯頓——英格蘭首位使用印刷機印書的人", category: "Culture & Arts", category_zh: "文化與藝術", exams: [2,13] },
  { period: "Tudor", year: "~1534", era: "Tudor",
    fact: "Henry VIII established the Church of England (the Reformation) — Pope refused his divorce from Catherine of Aragon",
    fact_zh: "亨利八世建立英格蘭教會（宗教改革）——教皇拒絕批准他與阿拉貢的凱瑟琳離婚", category: "Religion & Church", category_zh: "宗教與教會", exams: [3,6,7] },
  { period: "Tudor", year: "~1536", era: "Tudor",
    fact: "Anne Boleyn executed at the Tower of London",
    fact_zh: "安·博林在倫敦塔被處決", category: "Religion & Church", category_zh: "宗教與教會", exams: [4] },
  { period: "Tudor", year: "~1558", era: "Tudor",
    fact: "Elizabeth I became Queen — Protestant; found balance between Catholic and extreme Protestant views",
    fact_zh: "伊利沙伯一世登基——新教徒；在天主教與極端新教之間尋求平衡", category: "Religion & Church", category_zh: "宗教與教會", exams: [6,13] },
  { period: "Tudor", year: "~1585", era: "Tudor",
    fact: "English settlers began colonising the eastern coast of America under Elizabeth I",
    fact_zh: "伊利沙伯一世時期英格蘭定居者開始殖民美洲東海岸", category: "Trade & Empire", category_zh: "貿易與帝國", exams: [6] },
  { period: "Tudor", year: "1588", era: "Tudor",
    fact: "English defeated the Spanish Armada sent by Spain to conquer England",
    fact_zh: "英格蘭擊敗西班牙派遣征服英格蘭的無敵艦隊", category: "Wars & Conflicts", category_zh: "戰爭與衝突", exams: [1,8,13] },

  // STUART
  { period: "Stuart", year: "1603", era: "Stuart",
    fact: "James I (King of Scotland) became King of England — united the crowns",
    fact_zh: "詹姆斯一世（蘇格蘭國王）成為英格蘭國王——兩國王冠合一",
    category: "Government & Law", category_zh: "政府與法律", exams: [13], forRegions: true },
  { period: "Stuart", year: "1611", era: "Stuart",
    fact: "King James I — Authorised (King James) Version of the Bible",
    fact_zh: "詹姆斯一世——欽定版（詹姆斯王）聖經", category: "Religion & Church", category_zh: "宗教與教會", exams: [12] },
  { period: "Stuart", year: "1642", era: "Stuart",
    fact: "English Civil War — Cavaliers (Charles I supporters) vs Roundheads; battles of Marston Moor & Naseby",
    fact_zh: "英格蘭內戰——保王黨（查理一世支持者）對抗圓顱黨；馬斯頓荒原及納斯比之役", category: "Wars & Conflicts", category_zh: "戰爭與衝突", exams: [4,7,15] },
  { period: "Stuart", year: "1649", era: "Stuart",
    fact: "Charles I executed after the Civil War — England briefly became a republic",
    fact_zh: "內戰後查理一世被處決——英格蘭短暫成為共和國", category: "Government & Law", category_zh: "政府與法律", exams: [6,17] },
  { period: "Stuart", year: "~1650s", era: "Stuart",
    fact: "Oliver Cromwell given the title of Lord Protector (ruled England as a republic)",
    fact_zh: "奧利弗·克倫威爾獲封護國公頭銜（以共和制統治英格蘭）", category: "Government & Law", category_zh: "政府與法律", exams: [1] },
  { period: "Stuart", year: "~1651", era: "Stuart",
    fact: "Charles II hid in an oak tree after Civil War defeat, then escaped to Europe",
    fact_zh: "內戰失敗後查理二世躲藏在橡樹中，其後逃往歐洲", category: "Culture & Arts", category_zh: "文化與藝術", exams: [5,13] },
  { period: "Stuart", year: "1666", era: "Stuart",
    fact: "Great Fire of London during Charles II's reign; St Paul's Cathedral rebuilt by Sir Christopher Wren",
    fact_zh: "查理二世統治期間發生倫敦大火；聖保羅大教堂由克里斯托弗·雷恩爵士重建", category: "Culture & Arts", category_zh: "文化與藝術", exams: [4,11] },
  { period: "Stuart", year: "1688", era: "Stuart",
    fact: "The Glorious Revolution — William of Orange (from Netherlands) invited to invade England; bloodless takeover",
    fact_zh: "光榮革命——奧蘭治的威廉（來自荷蘭）應邀入侵英格蘭；不流血奪權", category: "Government & Law", category_zh: "政府與法律", exams: [5,16,17] },
  { period: "Stuart", year: "1689", era: "Stuart",
    fact: "Bill of Rights confirmed — did NOT give women the right to vote; did NOT give all adult men the vote",
    fact_zh: "《權利法案》確立——並未賦予女性投票權；亦未賦予所有成年男性投票權", category: "Government & Law", category_zh: "政府與法律", exams: [1,7] },
  { period: "Stuart", year: "1689", era: "Stuart",
    fact: "Habeas Corpus Act — gave everyone the right to a court hearing",
    fact_zh: "《人身保護令法》——賦予每人接受法庭聆訊的權利", category: "Government & Law", category_zh: "政府與法律", exams: [10] },
  { period: "Stuart", year: "1689+", era: "Stuart",
    fact: "Constitutional monarchy established after the Glorious Revolution",
    fact_zh: "光榮革命後確立君主立憲制", category: "Government & Law", category_zh: "政府與法律", exams: [10] },
  { period: "Stuart", year: "1690", era: "Stuart",
    fact: "Battle of the Boyne — James II defeated",
    fact_zh: "博因河戰役——詹姆斯二世戰敗",
    category: "Wars & Conflicts", category_zh: "戰爭與衝突", exams: [17], forRegions: true },
  { period: "Stuart", year: "~1692", era: "Stuart",
    fact: "Massacre of the MacDonalds of Glencoe — killed for not taking the oath",
    fact_zh: "格倫科麥當勞氏族大屠殺——因拒絕宣誓而遭殺害",
    category: "Wars & Conflicts", category_zh: "戰爭與衝突", exams: [7], forRegions: true },
  { period: "Stuart", year: "1707", era: "Stuart",
    fact: "Act of Union — united England and Scotland",
    fact_zh: "《聯合法案》——英格蘭與蘇格蘭合併",
    category: "Government & Law", category_zh: "政府與法律", exams: [], forRegions: true },
  { period: "Stuart", year: "1745", era: "Stuart",
    fact: "Bonnie Prince Charlie raised an army with support from Highland clansmen",
    fact_zh: "英俊王子查理在高地氏族支持下起兵",
    category: "Wars & Conflicts", category_zh: "戰爭與衝突", exams: [3,13], forRegions: true },

  // 18TH CENTURY
  { period: "18th Century", year: "1680–1720", era: "18th Century",
    fact: "Huguenot refugees fled to Britain from France",
    fact_zh: "胡格諾教徒難民從法國逃往英國", category: "Society & Health", category_zh: "社會與健康", exams: [12] },
  { period: "18th Century", year: "~1700s", era: "18th Century",
    fact: "Manufacturing was the biggest source of employment in the 18th century",
    fact_zh: "製造業是18世紀最大的就業來源", category: "Science & Industry", category_zh: "科學與工業", exams: [7] },
  { period: "18th Century", year: "~1760s+", era: "18th Century",
    fact: "Industrial Revolution — steam power drove rapid development; canals built to link factories to towns and ports",
    fact_zh: "工業革命——蒸汽動力推動快速發展；運河連接工廠、城鎮和港口", category: "Science & Industry", category_zh: "科學與工業", exams: [9,14] },
  { period: "18th Century", year: "~1770s", era: "18th Century",
    fact: "The Enlightenment — new ideas in politics, philosophy and science. Adam Smith (economics), David Hume (philosophy)",
    fact_zh: "啟蒙運動——政治、哲學和科學的新思想。亞當·斯密（經濟學）、大衛·休謨（哲學）",
    category: "Culture & Arts", category_zh: "文化與藝術", exams: [5,14,17], forRegions: true },
  { period: "18th Century", year: "1776", era: "18th Century",
    fact: "American colonies declared independence — 'no taxation without representation'",
    fact_zh: "美洲殖民地宣布獨立——「無代表則不納稅」", category: "Rights & Reform", category_zh: "權利與改革", exams: [3,15] },

  // 19TH CENTURY
  { period: "19th Century", year: "1805", era: "19th Century",
    fact: "Battle of Trafalgar — Admiral Nelson died defeating the French and Spanish fleets",
    fact_zh: "特拉法加戰役——納爾遜海軍上將在擊敗法西聯合艦隊時陣亡", category: "Wars & Conflicts", category_zh: "戰爭與衝突", exams: [5,14] },
  { period: "19th Century", year: "1807", era: "19th Century",
    fact: "Abolition of the slave trade in Britain",
    fact_zh: "英國廢除奴隸貿易", category: "Rights & Reform", category_zh: "權利與改革", exams: [] },
  { period: "19th Century", year: "1815", era: "19th Century",
    fact: "Battle of Waterloo — last battle between Great Britain and France; Napoleon defeated",
    fact_zh: "滑鐵盧戰役——英法最後一場戰役；拿破崙戰敗", category: "Wars & Conflicts", category_zh: "戰爭與衝突", exams: [4,9] },
  { period: "19th Century", year: "1833", era: "19th Century",
    fact: "Emancipation Act abolished slavery throughout the British Empire",
    fact_zh: "《解放法案》廢除整個大英帝國的奴隸制度", category: "Rights & Reform", category_zh: "權利與改革", exams: [7,15] },
  { period: "19th Century", year: "1847", era: "19th Century",
    fact: "Factories Act — limited women and children to 10 hours of work per day",
    fact_zh: "《工廠法》——限制婦女和兒童每天工作不超過10小時", category: "Rights & Reform", category_zh: "權利與改革", exams: [17] },
  { period: "19th Century", year: "~1840s", era: "19th Century",
    fact: "Ireland famine caused by potato shortage — many Irish died or emigrated",
    fact_zh: "愛爾蘭馬鈴薯饑荒——大量愛爾蘭人死亡或移民", category: "Society & Health", category_zh: "社會與健康", exams: [17] },
  { period: "19th Century", year: "~1850s", era: "19th Century",
    fact: "Crimean War — first war extensively covered by the media; Florence Nightingale served as a nurse",
    fact_zh: "克里米亞戰爭——首場被媒體廣泛報道的戰爭；佛羅倫斯·南丁格爾擔任護士", category: "Society & Health", category_zh: "社會與健康", exams: [11,14] },
  { period: "19th Century", year: "1851", era: "19th Century",
    fact: "Great Exhibition held at the Crystal Palace in Hyde Park, London",
    fact_zh: "萬國博覽會在倫敦海德公園水晶宮舉行", category: "Culture & Arts", category_zh: "文化與藝術", exams: [9] },
  { period: "19th Century", year: "~1860s", era: "19th Century",
    fact: "Fenians — Irish people who favoured complete independence from the UK",
    fact_zh: "芬尼亞運動——主張愛爾蘭完全脫離英國獨立的愛爾蘭人", category: "Rights & Reform", category_zh: "權利與改革", exams: [15] },
  { period: "19th Century", year: "~1880s", era: "19th Century",
    fact: "Highland Clearances — Scottish landlords cleared small farms to create large sheep and cattle farms",
    fact_zh: "高地清洗——蘇格蘭地主清除小農場以建立大型牧場",
    category: "Rights & Reform", category_zh: "權利與改革", exams: [7], forRegions: true },
  { period: "19th Century", year: "1899–1902", era: "19th Century",
    fact: "Boer War in South Africa — British fought against the Boers (South African settlers)",
    fact_zh: "南非布爾戰爭——英國對抗布爾人（南非荷蘭裔定居者）", category: "Wars & Conflicts", category_zh: "戰爭與衝突", exams: [5,9] },

  // EARLY 20TH CENTURY
  { period: "Early 20th C", year: "1913", era: "Early 20th Century",
    fact: "British government promised Home Rule for Ireland (delayed until 1921 due to WWI)",
    fact_zh: "英國政府承諾愛爾蘭自治（因第一次世界大戰延至1921年）", category: "Rights & Reform", category_zh: "權利與改革", exams: [6] },
  { period: "Early 20th C", year: "1914", era: "Early 20th Century",
    fact: "WWI started — triggered by assassination of Archduke Franz Ferdinand of Austria",
    fact_zh: "第一次世界大戰爆發——由奧匈帝國皇儲弗朗茨·斐迪南大公遇刺引發", category: "Wars & Conflicts", category_zh: "戰爭與衝突", exams: [7] },
  { period: "Early 20th C", year: "1918", era: "Early 20th Century",
    fact: "WWI ended at 11:00 am on 11th November 1918",
    fact_zh: "第一次世界大戰於1918年11月11日上午11時結束", category: "Wars & Conflicts", category_zh: "戰爭與衝突", exams: [10,15] },
  { period: "Early 20th C", year: "1918", era: "Early 20th Century",
    fact: "Women over 30 given the right to vote — in recognition of their contribution to WWI",
    fact_zh: "30歲以上婦女獲得投票權——表彰她們對第一次世界大戰的貢獻",
    category: "Rights & Reform", category_zh: "權利與改革", exams: [2,10], forRegions: true },
  { period: "Early 20th C", year: "1921", era: "Early 20th Century",
    fact: "Ireland Home Rule enacted; partition of Ireland",
    fact_zh: "愛爾蘭自治法實施；愛爾蘭分治",
    category: "Rights & Reform", category_zh: "權利與改革", exams: [6], forRegions: true },
  { period: "Early 20th C", year: "1928", era: "Early 20th Century",
    fact: "Women given equal voting rights at 21 — the same as men",
    fact_zh: "21歲婦女獲得與男性平等的投票權",
    category: "Rights & Reform", category_zh: "權利與改革", exams: [1,4,9], forRegions: true },
  { period: "Early 20th C", year: "1930s", era: "Early 20th Century",
    fact: "Great Depression — shipbuilding industry badly affected",
    fact_zh: "大蕭條——造船業受到嚴重打擊", category: "Society & Health", category_zh: "社會與健康", exams: [3] },
  { period: "Early 20th C", year: "1930s", era: "Early 20th Century",
    fact: "Sir Frank Whittle invented the jet engine",
    fact_zh: "法蘭克·惠特爾爵士發明噴射引擎", category: "Science & Industry", category_zh: "科學與工業", exams: [1] },
  { period: "Early 20th C", year: "1930s", era: "Early 20th Century",
    fact: "Alan Turing invented the Turing machine (foundation of modern computing)",
    fact_zh: "艾倫·圖靈發明圖靈機（現代計算的基礎）", category: "Science & Industry", category_zh: "科學與工業", exams: [15] },
  { period: "Early 20th C", year: "1939", era: "Early 20th Century",
    fact: "Germany invaded Poland — WWII began",
    fact_zh: "德國入侵波蘭——第二次世界大戰爆發", category: "Wars & Conflicts", category_zh: "戰爭與衝突", exams: [3,5,8] },
  { period: "Early 20th C", year: "1940", era: "Early 20th Century",
    fact: "Battle of Britain — aerial battle; Germany bombed Britain; the Royal Air Force defended",
    fact_zh: "不列顛空戰——德國轟炸英國；英國皇家空軍奮力抵禦", category: "Wars & Conflicts", category_zh: "戰爭與衝突", exams: [6,11,13] },
  { period: "Early 20th C", year: "1940", era: "Early 20th Century",
    fact: "Dunkirk — evacuation of Allied soldiers from France (the 'Dunkirk spirit')",
    fact_zh: "敦刻爾克——盟軍士兵從法國撤離（「敦刻爾克精神」）", category: "Wars & Conflicts", category_zh: "戰爭與衝突", exams: [12] },
  { period: "Early 20th C", year: "1944", era: "Early 20th Century",
    fact: "Butler Act — introduced free secondary education in England and Wales",
    fact_zh: "《巴特勒法》——在英格蘭和威爾斯引入免費中學教育",
    category: "Rights & Reform", category_zh: "權利與改革", exams: [9], forRegions: true },
  { period: "Early 20th C", year: "1945", era: "Early 20th Century",
    fact: "WWII ended; Clement Attlee elected Prime Minister; United Nations set up",
    fact_zh: "第二次世界大戰結束；克萊門特·艾德禮當選首相；聯合國成立", category: "Wars & Conflicts", category_zh: "戰爭與衝突", exams: [14,16] },
  { period: "Early 20th C", year: "1949", era: "Early 20th Century",
    fact: "Ireland became a republic",
    fact_zh: "愛爾蘭成為共和國",
    category: "Rights & Reform", category_zh: "權利與改革", exams: [2], forRegions: true },

  // POST-WAR & MODERN
  { period: "Post-War", year: "1950s", era: "Post-War & Modern",
    fact: "Francis Crick co-discovered the structure of the DNA molecule",
    fact_zh: "法蘭西斯·克里克共同發現DNA分子結構", category: "Science & Industry", category_zh: "科學與工業", exams: [8,16] },
  { period: "Post-War", year: "1952", era: "Post-War & Modern",
    fact: "Ernest Rutherford led a team of scientists to split the atom for the first time",
    fact_zh: "歐內斯特·盧瑟福領導科學家團隊首次分裂原子", category: "Science & Industry", category_zh: "科學與工業", exams: [15] },
  { period: "Post-War", year: "1954", era: "Post-War & Modern",
    fact: "Sir Roger Bannister became the first man to run a mile in under 4 minutes",
    fact_zh: "羅傑·班尼斯特爵士成為首位在4分鐘內跑完一英里的人", category: "Culture & Arts", category_zh: "文化與藝術", exams: [3] },
  { period: "Post-War", year: "1960s", era: "Post-War & Modern",
    fact: "Swinging Sixties — The Beatles & Rolling Stones; social laws liberalised; pop art (David Hockney)",
    fact_zh: "搖擺的六十年代——披頭四和滾石樂隊；社會法律自由化；普普藝術（大衛·霍克尼）", category: "Culture & Arts", category_zh: "文化與藝術", exams: [2,8,12,15] },
  { period: "Post-War", year: "1966", era: "Post-War & Modern",
    fact: "England won the Football World Cup; captain Bobby Moore",
    fact_zh: "英格蘭贏得世界盃足球賽；隊長博比·摩爾", category: "Culture & Arts", category_zh: "文化與藝術", exams: [1] },
  { period: "Post-War", year: "1972", era: "Post-War & Modern",
    fact: "Mary Peters won Olympic gold medal at the Munich Games",
    fact_zh: "瑪麗·彼得斯在慕尼黑奧運會奪得金牌", category: "Culture & Arts", category_zh: "文化與藝術", exams: [15] },
  { period: "Post-War", year: "1979", era: "Post-War & Modern",
    fact: "Margaret Thatcher became the first female Prime Minister (longest serving PM of the 20th century)",
    fact_zh: "瑪格麗特·戴卓爾成為首位女首相（20世紀任期最長的首相）",
    category: "Government & Law", category_zh: "政府與法律", exams: [1,11,17], forRegions: true },
  { period: "Post-War", year: "1990s", era: "Post-War & Modern",
    fact: "John Major played an important part in the Northern Ireland peace process",
    fact_zh: "約翰·馬卓安在北愛爾蘭和平進程中扮演重要角色",
    category: "Government & Law", category_zh: "政府與法律", exams: [16], forRegions: true },
  { period: "Post-War", year: "1997", era: "Post-War & Modern",
    fact: "Tony Blair (Labour) introduced the Scottish Parliament and the Welsh Assembly",
    fact_zh: "托尼·貝理雅（工黨）引入蘇格蘭議會和威爾斯議會",
    category: "Government & Law", category_zh: "政府與法律", exams: [16], forRegions: true },
  { period: "Post-War", year: "2002", era: "Post-War & Modern",
    fact: "Winston Churchill voted the Greatest Briton of all time",
    fact_zh: "溫斯頓·邱吉爾被選為史上最偉大的英國人", category: "Culture & Arts", category_zh: "文化與藝術", exams: [4,12] },
  { period: "Post-War", year: "2003", era: "Post-War & Modern",
    fact: "The Lord of the Rings by J.R.R. Tolkien voted the country's best-loved novel",
    fact_zh: "托爾金的《魔戒》被選為全國最受歡迎的小說", category: "Culture & Arts", category_zh: "文化與藝術", exams: [5] },
  { period: "Post-War", year: "2010", era: "Post-War & Modern",
    fact: "Conservative–Liberal Democrat coalition government formed",
    fact_zh: "保守黨與自由民主黨組成聯合政府", category: "Government & Law", category_zh: "政府與法律", exams: [6] },
  { period: "Post-War", year: "2012", era: "Post-War & Modern",
    fact: "Olympic Games held in the UK (third time UK has hosted)",
    fact_zh: "奧林匹克運動會在英國舉行（第三次主辦）", category: "Culture & Arts", category_zh: "文化與藝術", exams: [12,14] },
];
