// Life in the UK Test — All Q&A data from Exams 1–17
// Source: lifeintheuktestweb.co.uk

const REGIONS_DATA = {
  england: [
    { question: "Patron Saint of England?", answer: "St George", exams: [10] },
    { question: "St George's Day?", answer: "23rd April", exams: [13] },
    { question: "Flower symbol of England?", answer: "Rose", exams: [16] },
    { question: "Where is Big Ben located?", answer: "Houses of Parliament", exams: [1] },
    { question: "Where are the Crown Jewels kept?", answer: "Tower of London", exams: [2] },
    { question: "Who built the Tower of London?", answer: "William the Conqueror", exams: [6] },
    { question: "Who are the Beefeaters?", answer: "Tour guides at the Tower of London", exams: [3, 13] },
    { question: "What monument is in Wiltshire?", answer: "Stonehenge", exams: [14] },
    { question: "Where is the Eden Project?", answer: "Cornwall", exams: [5] },
    { question: "Largest National Park in England?", answer: "Lake District", exams: [3, 13] },
    { question: "UK's favourite view voted in 2007?", answer: "Lake District (Wastwater)", exams: [7] },
    { question: "Where is Theatreland located?", answer: "London's West End", exams: [11] },
    { question: "Where is the Tate Art Gallery?", answer: "London", exams: [12] },
    { question: "Where is the National Horseracing Museum?", answer: "Newmarket, Suffolk", exams: [13] },
    { question: "Who rebuilt St Paul's Cathedral after the Great Fire of London?", answer: "Sir Christopher Wren", exams: [11] },
    { question: "Who was born in Stratford-upon-Avon?", answer: "William Shakespeare", exams: [6, 9] },
    { question: "Cricket competition between England & Australia?", answer: "The Ashes", exams: [7] },
    { question: "Most famous tennis tournament in the UK?", answer: "Wimbledon", exams: [12] },
    { question: "Major horse-racing event in England?", answer: "Royal Ascot", exams: [7] },
    { question: "What type of event is the Grand National?", answer: "Horse Racing", exams: [4] },
    { question: "Who was first to print books in England?", answer: "William Caxton", exams: [2, 13] },
    { question: "Which court handles minor criminal cases in England?", answer: "Magistrates' Court", exams: [2] },
    { question: "How many jury members in England, Wales & Northern Ireland?", answer: "12", exams: [2] },
    { question: "Who was responsible for constructing the Great Western Railway?", answer: "Isambard Kingdom Brunel", exams: [16] },
    { question: "What event was held at Crystal Palace, Hyde Park, 1851?", answer: "The Great Exhibition", exams: [9] },
    { question: "Two forts that were part of Hadrian's Wall?", answer: "Vindolanda & Housesteads", exams: [15] },
    { question: "What type of theatre area is in London?", answer: "Theatreland (West End)", exams: [11] },
    { question: "Where is the Prime Minister's official home?", answer: "10 Downing Street", exams: [4] },
    { question: "What is Lent?", answer: "The 40 days before Easter", exams: [1, 7] },
    { question: "What was Sir Frank Whittle's invention in the 1930s?", answer: "Jet engine", exams: [1] },
    { question: "What did Isaac Newton discover?", answer: "Gravity", exams: [10, 16] },
    { question: "Who invented the World Wide Web?", answer: "Sir Tim Berners-Lee", exams: [12] },
    { question: "Who developed radar?", answer: "Robert Watson-Watt", exams: [4] },
    { question: "What did Alan Turing invent in the 1930s?", answer: "The Turing machine", exams: [15] },
    { question: "Who split the atom for the first time?", answer: "Ernest Rutherford", exams: [15] },
    { question: "Who co-discovered the structure of the DNA molecule?", answer: "Francis Crick", exams: [8, 16] },
    { question: "Which two pop groups were famous in the Swinging Sixties?", answer: "The Beatles & The Rolling Stones", exams: [15] },
    { question: "Who won the Football World Cup in 1966? (captain)", answer: "Bobby Moore (captain)", exams: [1] },
    { question: "Who was voted the Greatest Briton of all time in 2002?", answer: "Winston Churchill", exams: [4, 12] },
    { question: "Who was the first female Prime Minister of the UK?", answer: "Margaret Thatcher", exams: [1] },
    { question: "Who was the first British Prime Minister?", answer: "Sir Robert Walpole", exams: [14] },
    { question: "Who was Winston Churchill's successor as PM elected in 1945?", answer: "Clement Attlee", exams: [14] },
    { question: "Which two parties formed a coalition government in 2010?", answer: "Conservative Party & Liberal Democrats", exams: [6] },
    { question: "What is the Cenotaph?", answer: "A war memorial in Whitehall", exams: [1, 11] },
    { question: "Who designed the Cenotaph?", answer: "Sir Edwin Lutyens", exams: [8] },
    { question: "Where is the Cenotaph located?", answer: "Whitehall, London", exams: [11] },
    { question: "How many times has the UK hosted the Olympics?", answer: "3 times", exams: [14] },
    { question: "When did the UK host the Olympic Games most recently?", answer: "2012", exams: [12] },
    { question: "Who chairs debates at the House of Commons?", answer: "The Speaker", exams: [1] },
    { question: "What are the two Houses of Parliament?", answer: "House of Commons & House of Lords", exams: [4] },
    { question: "Who appoints life peers in the House of Lords?", answer: "The monarch", exams: [14] },
    { question: "Does Britain have a written constitution?", answer: "No", exams: [10] },
    { question: "Is the BBC controlled by the government?", answer: "No", exams: [12] },
    { question: "How often are UK general elections held?", answer: "Every 5 years", exams: [4] },
    { question: "What is the minimum age to serve on a jury?", answer: "18", exams: [1] },
    { question: "How is a jury selected?", answer: "Randomly from the electoral register", exams: [1] },
    { question: "What is a bank holiday?", answer: "A public holiday when banks and many businesses are closed", exams: [1] },
    { question: "What will you be given to vote before a general election?", answer: "A poll card", exams: [1] },
    { question: "What type of media must give balanced political coverage?", answer: "Television & Radio", exams: [1, 4] },
    { question: "What is canvassing?", answer: "Persuading people to vote for a political party", exams: [5] },
    { question: "Minimum age to stand as an MP?", answer: "18", exams: [9] },
    { question: "What is the Union Jack?", answer: "The Flag of the United Kingdom", exams: [12] },
  ],

  scotland: [
    { question: "Patron Saint of Scotland?", answer: "St Andrew", exams: [1] },
    { question: "St Andrew's Day?", answer: "30th November", exams: [11] },
    { question: "Capital city of Scotland?", answer: "Edinburgh", exams: [7] },
    { question: "Flower symbol of Scotland?", answer: "Thistle", exams: [8] },
    { question: "What is Hogmanay?", answer: "New Year's Eve in Scotland", exams: [3, 9, 14] },
    { question: "Song sung at New Year in UK?", answer: "Auld Lang Syne", exams: [15] },
    { question: "What type of church is the Church of Scotland?", answer: "Presbyterian", exams: [5] },
    { question: "Where did golf originate?", answer: "Scotland", exams: [2, 5] },
    { question: "Traditional food from Scotland?", answer: "Haggis", exams: [6] },
    { question: "What did John Logie Baird (Scottish) invent?", answer: "Television", exams: [2] },
    { question: "Where is Loch Lomond & Trossachs National Park?", answer: "Scotland", exams: [10] },
    { question: "Where is Skara Brae?", answer: "Scotland", exams: [17] },
    { question: "Where is Crathes Castle?", answer: "Scotland", exams: [13] },
    { question: "Where does the Edinburgh Fringe festival take place?", answer: "Edinburgh", exams: [10] },
    { question: "Where does the Scottish Grand National take place?", answer: "Ayr", exams: [10] },
    { question: "How many jury members in Scotland?", answer: "15", exams: [7] },
    { question: "Which court handles minor criminal cases in Scotland?", answer: "Justice of the Peace Court", exams: [6] },
    { question: "What church did Scotland establish in 1560?", answer: "A Protestant church", exams: [11] },
    { question: "Who defeated the English at the Battle of Bannockburn (1314)?", answer: "Robert the Bruce", exams: [7, 12] },
    { question: "Who supported Bonnie Prince Charlie in 1745?", answer: "Clansmen from the Scottish Highlands", exams: [3, 13] },
    { question: "What were the Highland Clearances?", answer: "Landlords destroyed small farms to make space for sheep & cattle", exams: [7] },
    { question: "Which Scottish clan was killed for not taking the oath?", answer: "MacDonalds of Glencoe", exams: [7] },
    { question: "What can the Scottish Parliament legislate on?", answer: "Education (not Defence or Immigration)", exams: [17] },
    { question: "What areas can devolved administrations pass laws on?", answer: "Health & Education", exams: [7] },
    { question: "Who was supported by clansmen and raised army in 1745?", answer: "Bonnie Prince Charlie", exams: [3] },
    { question: "What did Adam Smith develop ideas about during the Enlightenment?", answer: "Economics", exams: [14] },
    { question: "What did David Hume contribute to during the Enlightenment?", answer: "Philosophy", exams: [17] },
  ],

  wales: [
    { question: "Patron Saint of Wales?", answer: "St David", exams: [3] },
    { question: "St David's Day?", answer: "1st March", exams: [8] },
    { question: "Capital city of Wales?", answer: "Cardiff", exams: [3] },
    { question: "Flower symbol of Wales?", answer: "Daffodil", exams: [4] },
    { question: "Where is Snowdonia located?", answer: "Wales", exams: [3] },
    { question: "Where is Swansea located?", answer: "Wales", exams: [6] },
    { question: "Does Wales have its own established church?", answer: "No", exams: [3, 10] },
    { question: "How many members in the Welsh Government?", answer: "60", exams: [10] },
    { question: "How often are Welsh Government members elected?", answer: "Every 4 years", exams: [8] },
    { question: "What two countries developed Concorde?", answer: "Britain & France", exams: [3, 14] },
    { question: "What is Caernarfon Castle associated with?", answer: "Wales", exams: [13] },
    { question: "Who wrote 'The Daffodils' (inspired by Daffodils)?", answer: "William Wordsworth", exams: [11] },
  ],

  northernIreland: [
    { question: "Patron Saint of Northern Ireland?", answer: "St Patrick", exams: [5] },
    { question: "St Patrick's Day?", answer: "17th March", exams: [14] },
    { question: "Is St Patrick's Day a public holiday in Northern Ireland?", answer: "Yes", exams: [2] },
    { question: "Capital city of Northern Ireland?", answer: "Belfast", exams: [9] },
    { question: "Flower symbol of Northern Ireland?", answer: "Shamrock", exams: [9] },
    { question: "Where is the Giant's Causeway?", answer: "Northern Ireland", exams: [16] },
    { question: "Traditional food of Northern Ireland?", answer: "Ulster Fry", exams: [14] },
    { question: "Does Northern Ireland have its own established church?", answer: "No", exams: [6] },
    { question: "Does Northern Ireland have its own banknotes?", answer: "Yes — valid everywhere in the UK", exams: [2, 8] },
    { question: "How many members in the Northern Ireland Assembly?", answer: "90", exams: [12] },
    { question: "How is the Northern Ireland Parliament elected?", answer: "Proportional representation", exams: [14] },
    { question: "What can the NI Assembly NOT decide on?", answer: "Immigration & Defence", exams: [11] },
    { question: "Has the UK government ever suspended the NI Assembly?", answer: "Yes", exams: [11] },
    { question: "Who introduced the Scottish Parliament and Welsh Assembly?", answer: "Tony Blair", exams: [16] },
    { question: "Who followed Thatcher and helped with the NI peace process?", answer: "John Major", exams: [16] },
    { question: "Youth Court in NI heard by?", answer: "Up to 3 specially trained magistrates or a District Judge", exams: [15, 17] },
  ]
};

const TIMELINE_DATA = [
  // PREHISTORIC
  { period: "Stone Age", year: "~800,000 BC", era: "Prehistoric", fact: "First people in Britain were hunter-gatherers", exams: [7] },
  { period: "Neolithic", year: "~4,000 BC", era: "Prehistoric", fact: "First farmers came to Britain from South-East Europe (~6,000 years ago)", exams: [2, 15] },
  { period: "Iron Age", year: "~800 BC", era: "Prehistoric", fact: "First coins minted in Britain, showing names of Iron Age kings", exams: [6, 11, 12] },
  { period: "Ancient", year: "~3,000 BC", era: "Prehistoric", fact: "Stonehenge built in Wiltshire", exams: [14] },
  { period: "Ancient", year: "~3,000 BC", era: "Prehistoric", fact: "Skara Brae – prehistoric settlement in Scotland", exams: [17] },

  // ROMAN
  { period: "Roman", year: "55 BC", era: "Roman Britain", fact: "Julius Caesar led the first invasion of Britain", exams: [2] },
  { period: "Roman", year: "~AD 60", era: "Roman Britain", fact: "Boudicca – tribal leader who fought against the Romans", exams: [4, 13, 14] },
  { period: "Roman", year: "~AD 122", era: "Roman Britain", fact: "Emperor Hadrian built a wall in northern England to keep out the Picts", exams: [10] },
  { period: "Roman", year: "AD 410", era: "Roman Britain", fact: "Romans left Britain", exams: [16] },

  // ANGLO-SAXON & VIKING
  { period: "Anglo-Saxon", year: "After AD 410", era: "Anglo-Saxon & Viking", fact: "The Jutes came to Britain from northern Europe after the Romans left", exams: [16] },
  { period: "Anglo-Saxon", year: "~9th century", era: "Anglo-Saxon & Viking", fact: "King Alfred the Great united Anglo-Saxon kingdoms and defeated the Vikings", exams: [2, 13] },

  // NORMAN
  { period: "Norman", year: "1066", era: "Norman Conquest", fact: "Battle of Hastings — last successful foreign invasion of England; the Norman Conquest", exams: [2, 7] },
  { period: "Norman", year: "1066", era: "Norman Conquest", fact: "William the Conqueror (from France) built the Tower of London (White Tower)", exams: [6, 16, 17] },
  { period: "Norman", year: "~1086", era: "Norman Conquest", fact: "Domesday Book written after the Norman Conquest — tells how people lived in England", exams: [11, 15] },
  { period: "Norman", year: "Post-1066", era: "Norman Conquest", fact: "English language developed from Anglo-Saxon + Norman French", exams: [11, 15] },

  // MEDIEVAL
  { period: "Medieval", year: "1215", era: "Medieval", fact: "Magna Carta created — restricted the King's power", exams: [2, 8] },
  { period: "Medieval", year: "~1300s", era: "Medieval", fact: "Geoffrey Chaucer wrote the Canterbury Tales", exams: [4, 10, 13] },
  { period: "Medieval", year: "1314", era: "Medieval", fact: "Battle of Bannockburn — Robert the Bruce defeated the English; Scotland remained unconquered", exams: [7, 12] },
  { period: "Medieval", year: "1348", era: "Medieval", fact: "Black Death (plague) — one third of the population of England died", exams: [6, 17] },
  { period: "Medieval", year: "~1337–1453", era: "Medieval", fact: "Hundred Years War with France", exams: [3] },
  { period: "Medieval", year: "~1455–1485", era: "Medieval", fact: "Wars of the Roses — House of York vs House of Lancaster", exams: [1] },

  // TUDOR
  { period: "Tudor", year: "~1476", era: "Tudor", fact: "William Caxton — first person to print books in England using a printing press", exams: [2, 13] },
  { period: "Tudor", year: "~1534", era: "Tudor", fact: "Henry VIII established the Church of England (the Reformation) — Pope refused his divorce from Catherine of Aragon", exams: [3, 6, 7] },
  { period: "Tudor", year: "~1536", era: "Tudor", fact: "Anne Boleyn executed at the Tower of London", exams: [4] },
  { period: "Tudor", year: "~1540s", era: "Tudor", fact: "Reformation — movement against the Pope's authority", exams: [7, 9, 16] },
  { period: "Tudor", year: "~1558", era: "Tudor", fact: "Elizabeth I became Queen — Protestant; found balance between Catholic and extreme Protestant views", exams: [6, 13] },
  { period: "Tudor", year: "~1585", era: "Tudor", fact: "English settlers began colonising the eastern coast of America under Elizabeth I", exams: [6] },
  { period: "Tudor", year: "1588", era: "Tudor", fact: "English defeated the Spanish Armada sent by Spain to conquer England", exams: [1, 8, 13] },

  // STUART
  { period: "Stuart", year: "1603", era: "Stuart", fact: "James I (King of Scotland) became King of England — united the crowns", exams: [13] },
  { period: "Stuart", year: "1611", era: "Stuart", fact: "King James I — Authorised (King James) Version of the Bible", exams: [12] },
  { period: "Stuart", year: "1642", era: "Stuart", fact: "English Civil War — Cavaliers (Charles I supporters) vs Roundheads; battles of Marston Moor & Naseby", exams: [4, 7, 15] },
  { period: "Stuart", year: "1649", era: "Stuart", fact: "Charles I executed after the Civil War — England briefly became a republic", exams: [6, 17] },
  { period: "Stuart", year: "~1650s", era: "Stuart", fact: "Oliver Cromwell given the title of Lord Protector (ruled England as a republic)", exams: [1] },
  { period: "Stuart", year: "~1651", era: "Stuart", fact: "Charles II hid in an oak tree after Civil War defeat, then escaped to Europe", exams: [5, 13] },
  { period: "Stuart", year: "1660", era: "Stuart", fact: "Restoration — Charles II became King (the Restoration)", exams: [5] },
  { period: "Stuart", year: "1666", era: "Stuart", fact: "Great Fire of London during Charles II's reign; St Paul's Cathedral rebuilt by Sir Christopher Wren", exams: [4, 11] },
  { period: "Stuart", year: "1688", era: "Stuart", fact: "The Glorious Revolution — William of Orange (from Netherlands) invited to invade England; bloodless takeover", exams: [5, 16, 17] },
  { period: "Stuart", year: "1689", era: "Stuart", fact: "Bill of Rights confirmed — did NOT give women the right to vote; did NOT give all adult men the vote", exams: [1, 7] },
  { period: "Stuart", year: "1689", era: "Stuart", fact: "Habeas Corpus Act — gave everyone the right to a court hearing", exams: [10] },
  { period: "Stuart", year: "1689+", era: "Stuart", fact: "Constitutional monarchy established after the Glorious Revolution", exams: [10] },
  { period: "Stuart", year: "1690", era: "Stuart", fact: "Battle of the Boyne — James II defeated", exams: [17] },
  { period: "Stuart", year: "~1692", era: "Stuart", fact: "Massacre of the MacDonalds of Glencoe — killed for not taking the oath", exams: [7] },
  { period: "Stuart", year: "1707", era: "Stuart", fact: "Act of Union — united England and Scotland", exams: [] },
  { period: "Stuart", year: "1745", era: "Stuart", fact: "Bonnie Prince Charlie raised an army with support from Highland clansmen", exams: [3, 13] },

  // 18TH CENTURY
  { period: "18th Century", year: "1680–1720", era: "18th Century", fact: "Huguenot refugees fled to Britain from France", exams: [12] },
  { period: "18th Century", year: "~1700s", era: "18th Century", fact: "Manufacturing was the biggest source of employment in the 18th century", exams: [7] },
  { period: "18th Century", year: "~1760s+", era: "18th Century", fact: "Industrial Revolution — steam power drove rapid development; canals built to link factories to towns and ports", exams: [9, 14] },
  { period: "18th Century", year: "~1770s", era: "18th Century", fact: "The Enlightenment — new ideas in politics, philosophy and science. Adam Smith (economics), David Hume (philosophy)", exams: [5, 14, 17] },
  { period: "18th Century", year: "1776", era: "18th Century", fact: "American colonies declared independence — 'no taxation without representation'", exams: [3, 15] },

  // 19TH CENTURY
  { period: "19th Century", year: "1805", era: "19th Century", fact: "Battle of Trafalgar — Admiral Nelson died defeating the French and Spanish fleets", exams: [5, 14] },
  { period: "19th Century", year: "1807", era: "19th Century", fact: "Abolition of the slave trade in Britain", exams: [] },
  { period: "19th Century", year: "1815", era: "19th Century", fact: "Battle of Waterloo — last battle between Great Britain and France; Napoleon defeated", exams: [4, 9] },
  { period: "19th Century", year: "1833", era: "19th Century", fact: "Emancipation Act abolished slavery throughout the British Empire", exams: [7, 15] },
  { period: "19th Century", year: "1847", era: "19th Century", fact: "Factories Act — limited women and children to 10 hours of work per day", exams: [17] },
  { period: "19th Century", year: "~1840s", era: "19th Century", fact: "Ireland famine caused by potato shortage — many Irish died or emigrated", exams: [17] },
  { period: "19th Century", year: "~1850s", era: "19th Century", fact: "Crimean War — first war extensively covered by the media; Florence Nightingale served as a nurse", exams: [11, 14] },
  { period: "19th Century", year: "1851", era: "19th Century", fact: "Great Exhibition held at the Crystal Palace in Hyde Park, London", exams: [9] },
  { period: "19th Century", year: "~1860s", era: "19th Century", fact: "Fenians — Irish people who favoured complete independence from the UK", exams: [15] },
  { period: "19th Century", year: "~1880s", era: "19th Century", fact: "Highland Clearances — Scottish landlords cleared small farms to create large sheep and cattle farms", exams: [7] },
  { period: "19th Century", year: "1899–1902", era: "19th Century", fact: "Boer War in South Africa — British fought against the Boers (South African settlers)", exams: [5, 9] },

  // EARLY 20TH CENTURY
  { period: "Early 20th C", year: "1913", era: "Early 20th Century", fact: "British government promised Home Rule for Ireland (delayed until 1921 due to WWI)", exams: [6] },
  { period: "Early 20th C", year: "1914", era: "Early 20th Century", fact: "WWI started — triggered by assassination of Archduke Franz Ferdinand of Austria", exams: [7] },
  { period: "Early 20th C", year: "1918", era: "Early 20th Century", fact: "WWI ended at 11:00 am on 11th November 1918", exams: [10, 15] },
  { period: "Early 20th C", year: "1918", era: "Early 20th Century", fact: "Women over 30 given the right to vote — in recognition of their contribution to WWI", exams: [2, 10] },
  { period: "Early 20th C", year: "1921", era: "Early 20th Century", fact: "Ireland Home Rule enacted; partition of Ireland", exams: [6] },
  { period: "Early 20th C", year: "1928", era: "Early 20th Century", fact: "Women given equal voting rights at 21 — the same as men", exams: [1, 4, 9] },
  { period: "Early 20th C", year: "1930s", era: "Early 20th Century", fact: "Great Depression — shipbuilding industry badly affected", exams: [3] },
  { period: "Early 20th C", year: "1930s", era: "Early 20th Century", fact: "Sir Frank Whittle invented the jet engine", exams: [1] },
  { period: "Early 20th C", year: "1930s", era: "Early 20th Century", fact: "Alan Turing invented the Turing machine (foundation of modern computing)", exams: [15] },
  { period: "Early 20th C", year: "1939", era: "Early 20th Century", fact: "Germany invaded Poland — WWII began", exams: [3, 5, 8] },
  { period: "Early 20th C", year: "1940", era: "Early 20th Century", fact: "Battle of Britain — aerial battle; Germany bombed Britain; the Royal Air Force defended", exams: [6, 11, 13] },
  { period: "Early 20th C", year: "1940", era: "Early 20th Century", fact: "Dunkirk — evacuation of Allied soldiers from France (the 'Dunkirk spirit')", exams: [12] },
  { period: "Early 20th C", year: "1944", era: "Early 20th Century", fact: "Butler Act — introduced free secondary education in England and Wales", exams: [9] },
  { period: "Early 20th C", year: "1945", era: "Early 20th Century", fact: "WWII ended; Clement Attlee elected Prime Minister; United Nations set up", exams: [14, 16] },
  { period: "Early 20th C", year: "1949", era: "Early 20th Century", fact: "Ireland became a republic", exams: [2] },

  // POST-WAR & MODERN
  { period: "Post-War", year: "1950s", era: "Post-War & Modern", fact: "Francis Crick co-discovered the structure of the DNA molecule", exams: [8, 16] },
  { period: "Post-War", year: "1952", era: "Post-War & Modern", fact: "Ernest Rutherford led a team of scientists to split the atom for the first time", exams: [15] },
  { period: "Post-War", year: "1954", era: "Post-War & Modern", fact: "Sir Roger Bannister became the first man to run a mile in under 4 minutes", exams: [3] },
  { period: "Post-War", year: "1960s", era: "Post-War & Modern", fact: "Swinging Sixties — The Beatles & Rolling Stones; social laws liberalised; pop art (David Hockney)", exams: [2, 8, 12, 15] },
  { period: "Post-War", year: "1966", era: "Post-War & Modern", fact: "England won the Football World Cup; captain Bobby Moore", exams: [1] },
  { period: "Post-War", year: "1972", era: "Post-War & Modern", fact: "Mary Peters won Olympic gold medal at the Munich Games", exams: [15] },
  { period: "Post-War", year: "1979", era: "Post-War & Modern", fact: "Margaret Thatcher became the first female Prime Minister (longest serving PM of the 20th century)", exams: [1, 11, 17] },
  { period: "Post-War", year: "1990s", era: "Post-War & Modern", fact: "John Major played an important part in the Northern Ireland peace process", exams: [16] },
  { period: "Post-War", year: "1997", era: "Post-War & Modern", fact: "Tony Blair (Labour) introduced the Scottish Parliament and the Welsh Assembly", exams: [16] },
  { period: "Post-War", year: "2002", era: "Post-War & Modern", fact: "Winston Churchill voted the Greatest Briton of all time", exams: [4, 12] },
  { period: "Post-War", year: "2003", era: "Post-War & Modern", fact: "The Lord of the Rings by J.R.R. Tolkien voted the country's best-loved novel", exams: [5] },
  { period: "Post-War", year: "2010", era: "Post-War & Modern", fact: "Conservative–Liberal Democrat coalition government formed", exams: [6] },
  { period: "Post-War", year: "2012", era: "Post-War & Modern", fact: "Olympic Games held in the UK (third time UK has hosted)", exams: [12, 14] },
];
